USE [master]
GO

/****** Object:  Database [SosyalMedyaVeritabanı]    Script Date: 25.05.2023 00:19:30 ******/
CREATE DATABASE [SosyalMedyaVeritabanı]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SosyalMedyaVeritabanı', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SosyalMedyaVeritabanı.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SosyalMedyaVeritabanı_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SosyalMedyaVeritabanı_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SosyalMedyaVeritabanı].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SosyalMedyaVeritabanı] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SosyalMedyaVeritabanı] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SosyalMedyaVeritabanı] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SosyalMedyaVeritabanı] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SosyalMedyaVeritabanı] SET ARITHABORT OFF 
GO

ALTER DATABASE [SosyalMedyaVeritabanı] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [SosyalMedyaVeritabanı] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SosyalMedyaVeritabanı] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SosyalMedyaVeritabanı] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SosyalMedyaVeritabanı] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SosyalMedyaVeritabanı] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SosyalMedyaVeritabanı] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SosyalMedyaVeritabanı] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SosyalMedyaVeritabanı] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SosyalMedyaVeritabanı] SET  ENABLE_BROKER 
GO

ALTER DATABASE [SosyalMedyaVeritabanı] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SosyalMedyaVeritabanı] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SosyalMedyaVeritabanı] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SosyalMedyaVeritabanı] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SosyalMedyaVeritabanı] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SosyalMedyaVeritabanı] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SosyalMedyaVeritabanı] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SosyalMedyaVeritabanı] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SosyalMedyaVeritabanı] SET  MULTI_USER 
GO

ALTER DATABASE [SosyalMedyaVeritabanı] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SosyalMedyaVeritabanı] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SosyalMedyaVeritabanı] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SosyalMedyaVeritabanı] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SosyalMedyaVeritabanı] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SosyalMedyaVeritabanı] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SosyalMedyaVeritabanı] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SosyalMedyaVeritabanı] SET  READ_WRITE 
GO

